import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { beforeAll, describe, expect, it } from 'vitest'
import { parseMovie } from '../src/box-reader'
import { inspect } from '../src/inspector'
import { remux } from '../src/remuxer'

function hasFfmpeg(): boolean {
  try {
    execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' })
    execFileSync('ffprobe', ['-version'], { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

const ffmpegAvailable = hasFfmpeg()

describe.skipIf(!ffmpegAvailable)('e2e: real MOV generated by ffmpeg', () => {
  let dir: string
  let movPath: string

  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'movconverter-e2e-'))
    movPath = join(dir, 'input.mov')
    execFileSync(
      'ffmpeg',
      [
        '-y',
        '-f',
        'lavfi',
        '-i',
        'testsrc=duration=1:size=128x72:rate=24',
        '-f',
        'lavfi',
        '-i',
        'sine=frequency=440:duration=1',
        '-c:v',
        'libx264',
        '-pix_fmt',
        'yuv420p',
        '-c:a',
        'aac',
        '-shortest',
        movPath,
      ],
      { stdio: 'ignore' },
    )
  })

  it('remuxes an H.264+AAC MOV into a valid MP4', async () => {
    const input = new Blob([readFileSync(movPath) as unknown as BlobPart])
    const movie = await parseMovie(input)
    const plan = inspect(movie)
    expect(plan.method).toBe('remux')

    const output = remux(movie, plan).blob
    const outPath = join(dir, 'output.mp4')
    writeFileSync(outPath, Buffer.from(await output.arrayBuffer()))

    // Container and streams as reported by ffprobe.
    const probe = JSON.parse(
      execFileSync(
        'ffprobe',
        ['-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', outPath],
        { encoding: 'utf8' },
      ),
    )
    expect(probe.format.format_name).toContain('mp4')
    const codecs = probe.streams.map((s: { codec_name: string }) => s.codec_name).sort()
    expect(codecs).toEqual(['aac', 'h264'])
    expect(Number(probe.format.duration)).toBeCloseTo(1, 1)

    // Full decode must produce no errors: proves media bytes were not corrupted.
    const decodeErrors = execFileSync('ffmpeg', ['-v', 'error', '-i', outPath, '-f', 'null', '-'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    expect(decodeErrors).toBe('')

    // Output must be faststart: moov before mdat.
    const reparsed = await parseMovie(output)
    const types = reparsed.topLevel.map((b) => b.type)
    expect(types.indexOf('moov')).toBeLessThan(types.indexOf('mdat'))
  })

  it('remuxed output decodes to the same frame checksums as the input', async () => {
    const input = new Blob([readFileSync(movPath) as unknown as BlobPart])
    const movie = await parseMovie(input)
    const output = remux(movie, inspect(movie)).blob
    const outPath = join(dir, 'output2.mp4')
    writeFileSync(outPath, Buffer.from(await output.arrayBuffer()))

    const hashOf = (path: string) =>
      execFileSync('ffmpeg', ['-v', 'error', '-i', path, '-map', '0', '-f', 'hash', '-'], {
        encoding: 'utf8',
      }).trim()
    // Identical decoded output proves the remux was lossless.
    expect(hashOf(outPath)).toBe(hashOf(movPath))
  })
})
